import threading


class TestThread(threading.Thread):
    thread_id: int = ...
    write_file: bool = ...
    def __init__(self, thread_id: int, write_file: bool, group=None, target=None, name=None, args=(), kwargs=None, *,
                 daemon=None):...
